default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info

stages:
  - build

build_job:
  stage: build
  script: |
    echo "Building the application"
    docker login registry.gitlab.com -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    docker build -t registry.gitlab.com/bijit-mondal/codeitup:$CI_COMMIT_SHA .
    docker push registry.gitlab.com/bijit-mondal/codeitup:$CI_COMMIT_SHA
  only:
    - deploy


