default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info

stages:
  - build
  - deploy

build_job:
  stage: build
  script: |
    echo "Building the application"
    echo $DOCKER_USERNAME
    echo $DOCKER_PASSWORD
    docker login registry.gitlab.com -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    docker build -t registry.gitlab.com/bijit-mondal/codeitup:$CI_COMMIT_SHA .
    docker push registry.gitlab.com/bijit-mondal/codeitup:$CI_COMMIT_SHA

deploy_job:
  stage: deploy
  script: |
    echo "Deploying the application"
    docker login registry.gitlab.com -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    docker pull registry.gitlab.com/bijit-mondal/codeitup:$CI_COMMIT_SHA
    docker rm -f registry.gitlab.com/bijit-mondal/codeitup
    docker run -d -p 8080:8080 registry.gitlab.com/bijit-mondal/codeitup:$CI_COMMIT_SHA
  tags:
    - linode-deploy-runner
  only:
    - deploy
