spring:
  mvc:
    static-path-pattern: /app/**
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE}
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
  mail:
    properties:
      mail:
        smtp:
          socketFactory:
            port: ${SMTP_PORT}
            class: javax.net.ssl.SSLSocketFactory
            fallback: 'false'
          auth: 'true'
    host: ${SMTP_SERVER}
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}

application:
  security:
    github:
      pat: ${GITHUB_PAT}
    rapidapi:
      key: ${JUDGE0_KEY}
      host: ${JUDGE0_HOST}
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

logging:
  level:
    org:
      springframework:
        cache: TRACE
