spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CodeitUp
    username: root
    password: "#bijit567mondaL"
  mail:
    properties:
      mail:
        smtp:
          socketFactory:
            port: '465'
            class: javax.net.ssl.SSLSocketFactory
            fallback: 'false'
          auth: 'true'
    host: smtp.gmail.com
    username: spoton.rkmvcc@gmail.com
    password: dbitoccibutjjxqp


application:
  security:
    rapidapi:
      key: d2f1c0383amshccab8a5243218b4p19de7fjsn4f0e22a3bc14
      host: 'judge0-ce.p.rapidapi.com'
    jwt:
      secret-key: mokg97dd5d590fd9531e09fa089f10ff1436efdc60f8c9f3331c26ab32006c33
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

logging:
  level:
    org:
      springframework:
        cache: TRACE